#!/bin/sh
#          
#              _          _  _   ___  
#  __   _____ (_) ___ ___| || | / _ \ 
#  \ \ / / _ \| |/ __/ _ \ || || (_) |
#   \ V / (_) | | (_|  __/__   _\__, |
#    \_/ \___/|_|\___\___|  |_|   /_/ 
                                   

[global/wm]
;https://github.com/jaagr/polybar/wiki/Configuration#global-wm-settings
margin-top = 0
margin-bottom = 0

[settings]
;https://github.com/jaagr/polybar/wiki/Configuration#application-settings
throttle-output = 5
throttle-output-for = 10
throttle-input-for = 30
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

; Define fallback values used by all module formats
format-foreground =#f8f8f2
format-background = #282a36	
format-underline =
format-overline =
format-spacing =
format-padding =
format-margin =
format-offset =

[colors]
; Nord theme ============
background =#1e1f29
foreground = #f8f8f2
alert =#9C9C9C
volume-min = #a3be8c
volume-med = #ebcb8b
volume-max = #bf616a
; =======================

; Gotham theme ==========
; background = #0a0f14
; foreground = #99d1ce
; alert = #d26937
; volume-min = #2aa889
; volume-med = #edb443
; volume-max = #c23127
; =======================

; INTRCPTR theme ============
;background = ${xrdb:color0:#222}
;background = #aa000000
;background-alt = #444
;foreground = ${xrdb:color7:#222}
;foreground = #fff
;foreground-alt = #555
;primary = #ffb52a
;secondary = #e60053
;alert = #bd2c40



################################################################################
################################################################################
############                  MAINBAR-BSPWM                         ############
################################################################################
################################################################################

[bar/mainbar-bspwm]
monitor = ${env:MONITOR}
;monitor-fallback = HDMI0
width = 99%
height = 24
offset-x = 0.25%
offset-y = 0.25%
radius = 8
fixed-center = true
bottom = false
separator = " "

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = #bd93f9	

wm-restack = bspwm
override-redirect = true

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

border-size = 0
;border-left-size = 0
;border-right-size = 25
;border-top-size = 0
;border-bottom-size = 25
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin-left = 0
module-margin-right = 3

;https://github.com/jaagr/polybar/wiki/Fonts
font-0 = "SauceCodePro Nerd Font:size=8:weight=semibold;3"
font-1 = "FontAwesome:size=6;0"
font-2 = "UbuntuMonoo Nerd  Font Mono Regular:size=8;0"
font-3 = "UbuntuMonoo Nerd  Font Mono Regular:size=8;0"

modules-left =  activity bspwm xwindow 
modules-center= xkeyboard caps num weather1
modules-right = popup-calendar pavolume cpu2 memory2 sysmenu 
tray-detached = false
tray-offset-x = 160
tray-offset-y = 0
tray-padding = 0
tray-maxsize = 14
tray-scale = 1.0
tray-position =  center
tray-background = ${colors.background}

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev


################################################################################
################################################################################
############                  MAINBAR-BSPWM-EXTRA                   ############
################################################################################
################################################################################

[bar/mainbar-bspwm-extra]
monitor = ${env:MONITOR}
;monitor-fallback = DP-1
width = 99%
height = 24
offset-x = 0.5%
offset-y = 0.5%
radius = 8
fixed-center = true
bottom = false
separator = " "

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = #bd93f9	

wm-restack = bspwm
override-redirect = true

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

border-size = 0
;border-left-size = 0
;border-right-size = 25
;border-top-size = 0
;border-bottom-size = 25
border-color = #0000000

padding-left = 0
padding-right = 1

module-margin-left = 0
module-margin-right = 3

;https://github.com/jaagr/polybar/wiki/Fonts
font-0 = "SauceCodePro Nerd Font:size=8:weight=semibold;3"
font-1 = "FontAwesome:size=6;0"
font-2 = "UbuntuMonoo Nerd  Font Mono Regular:size=8;0"
font-3 = "UbuntuMonoo Nerd  Font Mono Regular:size=8;0"

modules-left = bspwm xwindow
modules-center = spotify1  sysmenu  xkeyboard caps filesystem  
modules-right =  pavolume cpu2 memory2 
;tray-detached = false
;tray-offset-x = 0
;tray-offset-y = 0
;tray-padding = 1
;tray-maxsize = 14
;tray-scale = 1.0
;tray-position = right
;tray-background = ${colors.background}

scroll-up = bspwm-desknext
scroll-down = bspwm-deskprev

################################################################################
################################################################################
############                       MODULE BSPWM                     ############
################################################################################
################################################################################
[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = true
pin-workspaces = true

ws-icon-0 = 1;1 
ws-icon-1 = 2;2
ws-icon-2 = 3;3
ws-icon-3 = 4;4
ws-icon-4 = 5;5
ws-icon-5 = 6;6
ws-icon-6 = 7;7
ws-icon-7 = 8;8
ws-icon-8 = 9;9
ws-icon-9 = 10;10
ws-icon-default = "[] "


;ws-icon-0 = 1;
;ws-icon-1 = 2;
;ws-icon-2 = 3;
;ws-icon-3 = 4;
;ws-icon-4 = 5;
;ws-icon-5 = 6;
;ws-icon-6 = 7;
;ws-icon-7 = 8;
;ws-icon-8 = 9;
;ws-icon-9 = 10;
;ws-icon-default = " "



format = <label-state> <label-mode>

label-focused = %icon%
label-focused-background = ${colors.background}
label-focused-underline= #bd93f9	
label-focused-padding = 2
label-focused-foreground = ${colors.foreground}

label-occupied = %icon%
label-occupied-padding = 2
label-occupied-background = ${colors.background}

label-urgent = %icon%
label-urgent-padding = 2

label-empty = %icon%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 2
label-empty-background = ${colors.background}
label-monocle = "  "
label-monocle-foreground = ${colors.foreground}
label-tiled = "  "
label-tiled-foreground = ${colors.foreground}
label-fullscreen = "  "
label-fullscreen-foreground = ${colors.foreground}
label-floating = "  "
label-floating-foreground = ${colors.foreground}
label-pseudotiled = "  "
label-pseudotiled-foreground = ${colors.foreground}
label-locked = "  "
label-locked-foreground = ${colors.foreground}
label-sticky = "  "
label-sticky-foreground = ${colors.foreground}
label-private =  "     "
label-private-foreground = ${colors.foreground}

; Separator in between workspaces
;label-separator = |
;label-separator-padding = 10
;label-separator-foreground = #ffb52a

format-foreground = ${colors.foreground}
format-background = ${colors.background}
#################################################################################
[module/compton]
;https://github.com/jaagr/polybar/wiki/User-contributed-modules#compton
type = custom/script
exec = ~/.config/polybar/scripts/compton.sh
click-left = ~/.config/polybar/scripts/compton-toggle.sh
interval = 5
format-foreground = ${colors.foreground}
format-background = ${colors.background}
;format-underline = #00AF02
################################################################################
[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/scripts/cava.sh
format = <label>
format-font = 5
label = %output%
label-foreground = ${colors.foreground}
#################################################################################
[module/cpu2]
;https://github.com/jaagr/polybar/wiki/Module:-cpu
type = internal/cpu
; Seconds to sleep between updates
; Default: 1
interval = 1
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = " "
format-prefix-foreground = #cd1f3f
format-underline =  #1e1f29

label-font = 1

; Available tags:
;   <label> (default)
;   <bar-load>
;   <ramp-load>
;   <ramp-coreload>
format = <label>

format-padding = 2

; Available tokens:
;   %percentage% (default) - total cpu load
;   %percentage-cores% - load percentage for each core
;   %percentage-core[1-9]% - load percentage for specific core
label = Cpu %percentage:3%%
##############################################################################
[module/activity]
type = custom/text

content = "  "
content-foreground = ${color.fg}

click-left = rofi -no-config -no-lazy-grab -show drun -theme $HOME/.config/voice49/rofi/list_launcher.rasi
click-right = rofi -no-config -no-lazy-grab -show drun -theme $HOME/.config/voice49/rofi/list_launcher.rasi
########################################################################
[module/sysmenu]
type = custom/text

content =  "⏻"
content-foreground = ${color.fg}

click-left = $HOME/.config/rofipower/rofipower.sh
################################################################
[module/filesystem]
;https://github.com/jaagr/polybar/wiki/Module:-filesystem
type = internal/fs

; Mountpoints to display
mount-0 = /
;mount-1 = /home
;mount-2 = /var

; Seconds to sleep between updates
; Default: 30
interval = 30

; Display fixed precision values
; Default: false
fixed-values = false

; Spacing between entries
; Default: 2
spacing = 4

; Available tags:
;   <label-mounted> (default)
;   <bar-free>
;   <bar-used>
;   <ramp-capacity>
format-mounted = <label-mounted>
format-mounted-foreground = ${colors.foreground}
format-mounted-background = ${colors.background}
format-mounted-underline = 


; Available tokens:
;   %mountpoint%
;   %type%
;   %fsname%
;   %percentage_free%
;   %percentage_used%
;   %total%
;   %free%
;   %used%
; Default: %mountpoint% %percentage_free%%
label-mounted = %mountpoint% : %used% used of %total%

; Available tokens:
;   %mountpoint%
; Default: %mountpoint% is not mounted
label-unmounted = %mountpoint% not mounted
format-unmounted-foreground = ${colors.foreground}
format-unmounted-background = ${colors.background}
;format-unmounted-underline = ${colors.alert}
################################################################################
[module/kernel]
type = custom/script
exec = uname -r
tail = false
interval = 1024

format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = ""
format-prefix-foreground = ${colors.foreground}
format-underline =
################################################################################
[module/powermenu]
type = custom/text
format-foreground = ${colors.foreground}
format-background = ${colors.background}
content =  "⏻"
content-foreground = ${color.fg}

click-left = $HOME/.config/rofipower/rofipower.sh
#################################################################################
[module/memory1]
;https://github.com/jaagr/polybar/wiki/Module:-memory
type = internal/memory
interval = 1
; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %percentage_used%%
bar-used-indicator =
bar-used-width = 10
bar-used-foreground-0 = #3384d0
bar-used-fill = 
bar-used-empty = 
bar-used-empty-foreground = #000066

format = <label> <bar-used>
format-prefix = "  "
format-prefix-foreground = #3384d0
format-underline = 
format-foreground = ${colors.foreground}
format-background = ${colors.background}
################################################################################
[module/memory2]
;https://github.com/jaagr/polybar/wiki/Module:-memory
type = internal/memory
interval = 1
; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %percentage_used%%

format = Ram <label>
format-prefix = "  "
format-prefix-foreground = #3384d0
format-underline =
format-foreground = ${colors.foreground}
format-background = ${colors.background}
################################################################################
[module/memory3]
;https://github.com/jaagr/polybar/wiki/Module:-memory
type = internal/memory
interval = 1
; Available tokens:
;   %percentage_used% (default)
;   %percentage_free%
;   %gb_used%
;   %gb_free%
;   %gb_total%
;   %mb_used%
;   %mb_free%
;   %mb_total%
label = %gb_used%/%gb_free%

format = Mem <label>
format-prefix = "  "
format-prefix-foreground = #3384d0
format-underline = #3384d0
format-foreground = ${colors.foreground}
format-background = ${colors.background}
################################################################################
[module/mpd]
;https://github.com/jaagr/polybar/wiki/Module:-mpd
type = internal/mpd
;format-online =  "<label-song>   <icon-prev>  <icon-stop>  <toggle>  <icon-next>"
format-online =  "<label-song>  <bar-progress>"
;format-online =  "<label-song>  <bar-progress> <icon-prev>  <icon-stop>  <toggle>  <icon-next>"
icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
label-song-maxlen = 40
label-song-ellipsis = true
bar-progress-width = 10
bar-progress-indicator = 
bar-progress-fill = 
bar-progress-empty = 
bar-progress-fill-foreground = #ff0
bar-progress-fill-background = ${colors.background}
bar-progress-indicator-foreground = ${colors.foreground}
format-online-foreground = ${colors.foreground}
format-online-background = ${colors.background}
################################################################################
[module/pavolume]
type = custom/script
tail = true
label = %output%
exec = ~/.config/polybar/scripts/pavolume.sh --listen
click-right = exec pavucontrol
click-left = ~/.config/polybar/scripts/pavolume.sh --togmute
scroll-up = ~/.config/polybar/scripts/pavolume.sh --up
scroll-down = ~/.config/polybar/scripts/pavolume.sh --down
format-underline =  #bd93f9
format-foreground = ${colors.foreground}
format-background = ${colors.background}
################################################################################
[module/release]
type = custom/script
exec = (lsb_release -d | awk {'print $2'} ;echo " "; lsb_release -r | awk {'print $2'}) | tr -d '\n'
interval = 6000

format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = ""
format-prefix-foreground = ${colors.foreground}
format-underline = 
################################################################################
[module/sep]
; alternative separator
type = custom/text
content = 
content-foreground = ${colors.foreground}
content-background =  ${colors.background}
format-foreground = ${colors.foreground}
format-background = ${colors.background}
################################################################################
[module/spotify1]
;https://github.com/NicholasFeldman/dotfiles/blob/master/polybar/.config/polybar/spotify.sh
type = custom/script
exec = ~/.config/polybar/scripts/spotify1.sh
interval = 1

;format = <label>
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-padding = 2
format-underline = 
format-prefix = "  "
format-prefix-foreground = #0f0
label = %output:0:150%
################################################################################
[module/weather1]
type = custom/script
interval = 10
format = <label>
format-prefix = " "
format-prefix-foreground = 
format-underline = 
format-foreground = ${colors.foreground}
format-background = ${colors.background}
exec = python -u ~/.config/polybar/scripts/weather.py
tail = true
#################################################################################
[module/openweathermap-simple]
type = custom/script
exec = ~/.config/polybar/scripts/openweathermap-simple.sh
interval = 600
label-font = 3
font-2 = Weather Icons:size=12;1
format-foreground = 
format-background = ${colors.background}
format-underline = 
###############################################################################
[module/popup-calendar]
type = custom/script
exec = ~/.config/polybar/scripts/popup-calendar.sh
interval = 5
click-left = ~/.config/polybar/scripts/popup-calendar.sh --popup &                
click-right =
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-underline =                  
################################################################################
[module/xkeyboard]
;https://github.com/jaagr/polybar/wiki/Module:-xkeyboard
type = internal/xkeyboard
blacklist-0 = num lock 
blacklist-1 = caps lock

format-prefix = " "
format-prefix-foreground = ${colors.foreground}
format-prefix-background = ${colors.background}
format-prefix-underline = 	
format-foreground = ${colors.foreground}
format-background = ${colors.background}

label-layout = %layout%
label-layout-underline = 
label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${colors.background}
label-indicator-underline = ${colors.foreground}
################################################################################
[module/caps]
type = custom/script
interval = 0.5s
exec = ~/.config/polybar/scripts/cns.sh -c
format-foreground =  #f8f8f2	
################################################################################
[module/num]
type = custom/script
interval = 0.5s
exec = ~/.config/polybar/scripts/cns.sh -n
format-foreground = #f8f8f2	
##################################################################################
[module/scroll]
type = custom/script
interval = 0.5s
exec = ~/.config/polybar/scripts/cns.sh -s
format-foreground = #f8f8f2
################################################################################
[module/xwindow]
;https://github.com/jaagr/polybar/wiki/Module:-xwindow
type = internal/xwindow

; Available tokens:
;   %title%
; Default: %title%
label = %title%
label-maxlen = 50

format-foreground = ${colors.foreground}
format-background = ${colors.background}
